# Generated by Django 4.2.2 on 2023-09-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='movies/')),
                ('complete_tasks', models.BigIntegerField(default=0)),
                ('time_tasks', models.BigIntegerField(default=0)),
                ('level', models.BigIntegerField(default=0)),
                ('js_tasks', models.BigIntegerField(default=0)),
                ('js_aim', models.BigIntegerField(default=0)),
                ('js_speed', models.BigIntegerField(default=0)),
                ('js_avg', models.BigIntegerField(default=0)),
            ],
        ),
    ]
