# Generated by Django 4.2.2 on 2023-10-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('complete_tasks', models.BigIntegerField(default=0)),
                ('time_tasks', models.BigIntegerField(default=0)),
                ('level', models.BigIntegerField(default=0)),
                ('js_tasks', models.BigIntegerField(default=0)),
                ('js_aim', models.BigIntegerField(default=0)),
                ('js_speed', models.BigIntegerField(default=0)),
                ('js_avg', models.BigIntegerField(default=0)),
                ('c_tasks', models.BigIntegerField(default=0)),
                ('c_aim', models.BigIntegerField(default=0)),
                ('c_speed', models.BigIntegerField(default=0)),
                ('c_avg', models.BigIntegerField(default=0)),
                ('py_tasks', models.BigIntegerField(default=0)),
                ('py_aim', models.BigIntegerField(default=0)),
                ('py_speed', models.BigIntegerField(default=0)),
                ('py_avg', models.BigIntegerField(default=0)),
                ('user_id_stats', models.BigIntegerField()),
            ],
        ),
    ]
