# Generated by Django 4.2.2 on 2023-10-08 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats_user', serialize=False, to=settings.AUTH_USER_MODEL)),

                ('complete_tasks', models.BigIntegerField(default=0)),
                ('time_tasks', models.BigIntegerField(default=0)),
                ('level', models.BigIntegerField(default=0)),
                ('js_tasks', models.BigIntegerField(default=0)),
                ('js_aim', models.BigIntegerField(default=0)),
                ('js_speed', models.BigIntegerField(default=0)),
                ('js_avg', models.BigIntegerField(default=0)),
                ('c_tasks', models.BigIntegerField(default=0)),
                ('c_aim', models.BigIntegerField(default=0)),
                ('c_speed', models.BigIntegerField(default=0)),
                ('c_avg', models.BigIntegerField(default=0)),
                ('py_tasks', models.BigIntegerField(default=0)),
                ('py_aim', models.BigIntegerField(default=0)),
                ('py_speed', models.BigIntegerField(default=0)),
                ('py_avg', models.BigIntegerField(default=0)),
            ],
        ),
    ]
